import dotenv from "dotenv";
dotenv.config();

export default {
  PORT: process.env.PORT ?? 3008,
  META_JWT_TOKEN: process.env.META_JWT_TOKEN,
  META_NUMBER_ID: process.env.META_NUMBER_ID,
  META_VERIFY_TOKEN: process.env.META_VERIFY_TOKEN,
  META_VERSION: process.env.META_VERSION,

  BASE_URL_WORKI: process.env.BASE_URL_WORKI,

  API_KEY_FIREBASE: process.env.API_KEY_FIREBASE,
  AUTH_DOMAIN_FIREBASE: process.env.AUTH_DOMAIN_FIREBASE,
  PROJECT_ID_FIREBASE: process.env.PROJECT_ID_FIREBASE,
  STORAGE_BUCKET_FIREBASE: process.env.STORAGE_BUCKET_FIREBASE,
  MESSAGING_SENDER_ID_FIREBASE: process.env.MESSAGING_SENDER_ID_FIREBASE,
  APP_ID_FIREBASE: process.env.APP_ID_FIREBASE,

  URL_BASE_BOT: process.env.URL_BASE_BOT,
  URL_JOBS: process.env.URL_JOBS,

  OPENAI_API_KEY: process.env.OPENAI_API_KEY,
  OPENAI_MODEL: process.env.OPENAI_MODEL || "gpt-4o",
};
